jobshop/board/urls.py
# board/urls.py

from django.urls import path

from .views import ArticleList, ArticleDetail, ArticleDelete, ArticleCreate, ArticleUpdate

urlpatterns = [
    path('', ArticleList.as_view(), name='index'),
    path('create/', ArticleCreate.as_view(), name='create'),
    path('<int:pk>/', ArticleDetail.as_view(), name='detail'),
    path('<int:pk>/update/', ArticleUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', ArticleDelete.as_view(), name='delete'),
]

jobshop/company/urls.py
# company/urls.py

from django.urls import path

from .views import *

app_name = 'company'
urlpatterns = [
    path('', home, name='company.index'),
    path('product/regist/', comp_product_regist, name='company.product'),
    path('product/search/', comp_product_view, name='company.product.view'),
    path('product/list/all/', product_search, name='company.product_search'),
    path('product/list/edit/', prod_list_edit, name='company.prod_list_edit'),

    path('facility/list/', comp_production_view, name='company.facility'),
    path('facility/list/edit/', fac_list_edit, name='company.fac_list_edit'),
    path('facility/list/all/', comp_facility_all, name='company.comp_facility_all'),
    path('csv/facility/download/', comp_facility_csv_download, name='company.comp_facility_csv_download'),
    path('info/list/', comp_list_view, name='company.list'),
    path('excel/create/', comp_update_excel, name='create'),
    path('csv/create/', comp_update_csv, name='csvCreate'),
    path('modal/create/', comp_update_modal, name='company.comp_update_modal'),

    path('csv/comp/read/', comp_read_csv, name='company.comp_read_csv'),
    path('csv/comp/download/blank/', comp_csv_download_blank, name='company.comp_csv_download_blank'),
    path('csv/comp/download/', comp_csv_download, name='company.comp_csv_download'),
    path('avail/facility/', comp_avail_facility, name='company.comp_avail_facility'),
    path('csv/production/download/', comp_production_csv_download, name='company.comp_production_csv_download'),

    path('csv/prod/read/', prod_read_csv, name='company.prod_read_csv'),
    path('csv/prod/upload/', comp_prod_update_csv, name='company.comp_prod_update_csv'),
    path('csv/prod/download/', prod_csv_download, name='company.prod_csv_download'),
    path('csv/prod/download/blank/', prod_csv_download_blank, name='company.prod_csv_download_blank'),

    path('modal/prod/upload/', comp_prod_update_modal, name='company.comp_prod_update_modal'),
    path('csv/upload/', upload_file, name='upload'),
    path('delete/', delete, name='delete'),
]

jobshop/jobshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from frontend import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('logout/', views.logout, name='logout'),
    path('board/', views.board),
    path('test/', views.test),
    path('nav/', views.nav),
    path('footer/', views.footer),
    path('topbar/', views.topbar),
    path('board/', include('board.urls'), name='board'),
    path('company/', include('company.urls'), name='company'),
    path('schedule/', include('schedule.urls'), name='schedule'),
    path('common/', include('common.urls')),
    path('recommend/', include('recommend.urls')),
    path('order/', include('order.urls'), name='order'),
]
# 파일 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

jobshop/company/views.py
#-*- coding: utf-8 -*-
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView
from django.http import JsonResponse
from django.contrib import auth
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.encoding import smart_str
from openpyxl import load_workbook
from fileutils.forms import FileUploadCsv
from fileutils.models import FileUploadCsv as fileUploadCsv
from .models import *
from order.models import *
from common.views import id_generate, date_str, comma_str, money_count, regex
import pandas as pd
import json, csv, datetime
from urllib.parse import quote
from datetime import timedelta

# 설비정보등록 company Facility register HTML
def home(request):
    template_name = 'company/comp_regist.html'
    comp_list = Facility.objects.all()
    date = datetime.datetime.today() - timedelta(days=3)
    date = {
        "comp_list": comp_list,
        'dateFrom': date.strftime("%Y-%m-%d"),
        'path': '회사정보 / 설비정보등록'
    }
    return render(request, template_name, date)

# 설비정보검색 company Facility view HTML
def comp_list_view(request):
    template_name = 'company/comp_fac_list.html'
    date = datetime.datetime.today() - timedelta(days=3)
    comp_list = Facility.objects.filter(comp_id=request.user.groups.values('id')[0]['id'])
    information = Information.objects.get(comp_id=request.user.groups.values('id')[0]['id'])
    result_list = []
    for i in range(len(comp_list.values())):
        # comp_name = Information.objects.get(comp_id=comp_list[i].comp_id)
        comp_name = comp_list[i].comp_id.comp_name # comp_name.name
        result = {}
        result['comp_name'] = comp_name
        result['facility_name'] = comp_list[i].facility_name
        result['facility_id'] = comp_list[i].facility_id
        result['credibility'] = information.credibility
        result['address'] = information.address
        result['contact'] = information.contact
        result['email'] = information.email
        result_list.append(result)

    date = {
        "comp_list": result_list,
        'dateFrom': date.strftime("%Y-%m-%d"),
        'path': '회사정보 / 설비정보검색'
    }
    return render(request, template_name, date)

# 설비현황검색 company production view HTML
def comp_production_view(request):
    template_name = 'company/comp_prod_list.html'

    dateFrom, dateTo, order_list = comp_production_search(request)

    date = {
        "comp_list": order_list,
        'dateFrom': dateFrom,
        'dateTo': dateTo,
        'app_name': 'company',
        'path': '회사정보 / 설비현황검색'
    }

    return render(request, template_name, date)

# 설비정보검색 데이터 다운로드 csv
def comp_facility_csv_download(request):
    filename = request.user.groups.values('name')[0]['name'] + "_설비정보.csv"

    # response content type
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': "attachment;filename*=UTF-8''{}".format(quote(filename.encode('utf-8')))},
    )

    writer = csv.writer(response, csv.excel)
    response.write(u'\ufeff'.encode('utf8'))

    # write the headers
    writer.writerow([
        smart_str(u"회사명"),
        smart_str(u"설비 호기"),
    ])
    # get data from database or from text file....
    comp_list = Facility.objects.filter(comp_id=request.user.groups.values('id')[0]['id'])

    if not comp_list:
        return response
    else:
        for comp in comp_list:
            writer.writerow([
                smart_str(comp.comp_id.comp_name),
                smart_str(comp.facility_name),
            ])
    return response

# 설비현황검색 데이터 다운로드 csv
def comp_production_csv_download(request):
    filename = request.user.groups.values('name')[0]['name'] + "_설비현황.csv"

    # response content type
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': "attachment;filename*=UTF-8''{}".format(quote(filename.encode('utf-8')))},
    )

    writer = csv.writer(response, csv.excel)
    response.write(u'\ufeff'.encode('utf8'))

    # write the headers
    writer.writerow([
        smart_str(u"회사명"),
        smart_str(u"작업호기"),
        smart_str(u"작업시작일자"),
        smart_str(u"작업종료일자"),
        smart_str(u"고객요청기한"),
        smart_str(u"제품명"),
        smart_str(u"생산량(yd)"),
    ])
    # get data from database or from text file....
    dateFrom, dateTo, order_list = comp_production_search(request)
    if not order_list:
        return response
    else:
        for ord in order_list:
            writer.writerow([
                smart_str(ord['comp_name']),
                smart_str(ord['facility_name']),
                smart_str(ord['work_str_date']),
                smart_str(ord['work_end_date']),
                smart_str(ord['exp_date']),
                smart_str(ord['prod_name']),
                smart_str(ord['amount']),
            ])
    return response

# 설비현황작업범위검색
def comp_production_search(request):
    date = datetime.datetime.today() - timedelta(days=3)

    if 'dateFrom' in request.GET:
        sch_date_from = datetime.datetime.strptime(request.GET['dateFrom'], "%Y-%m-%d")
        sch_date_to = datetime.datetime.strptime(request.GET['dateTo'], "%Y-%m-%d")

        date_from = request.GET['dateFrom'].replace('-', '')
        date_to = request.GET['dateTo'].replace('-', '')

        order_list = OrderSchedule.objects.filter(sch_id__work_str_date__gte=date_from).filter(sch_id__comp_id=request.user.groups.values('id')[0]['id']).filter(use_yn='Y')

    else:
        sch_date_from = date
        sch_date_to = datetime.datetime.today()
        order_list = OrderSchedule.objects.filter(sch_id__work_str_date__gte=datetime.datetime.today().strftime(
                                                      "%Y%m%d")).filter(sch_id__comp_id=request.user.groups.values('id')[0]['id']).filter(use_yn='Y')
    #####################################################################
    using_facility_list = []

    for i in order_list:
        using_facility = Schedule.objects.raw(
            " SELECT * " +
            " FROM company_schedule" +
            " WHERE prod_id = '" + i.sch_id.prod_id + "'" +
            " AND SUBSTRING(sch_id, 4, 8) = '" + i.sch_id.sch_id[3:11] + "'"
                                                                         " AND COUNT = (" +
            " SELECT COUNT" +
            " FROM company_schedule" +
            " WHERE sch_id = '" + i.sch_id.sch_id + "'" +
            ") GROUP BY facility_id "
        )
        using_facility_list.append(list(using_facility))

    fac_name_list = []
    for i in using_facility_list:
        comma_list = []
        for j in i:
            comma_list.append(j.facility_id.facility_name)
        fac_name_list.append(comma_list)

    result_list = []
    for ord in range(len(order_list.values())):
        for i in using_facility_list:
            for j in i:
                if order_list[ord].order_id.prod_id == j.prod_id:
                    prod_name = Product.objects.filter(prod_id=j.prod_id)[0]
                    prod_name = prod_name.prod_name
                    result = {}
                    result['comp_id'] = j.comp_id.comp_id
                    result['comp_name'] = j.comp_id.comp_name
                    result['facility_name'] = str(fac_name_list[ord]).replace('[', '').replace(']', '') # j.facility_id.facility_name
                    result['work_str_date'] = date_str(j.work_str_date)
                    result['work_end_date'] = date_str(j.work_end_date)
                    result['amount'] = order_list[ord].order_id.amount
                    result['prod_name'] = prod_name
                    result['exp_date'] = date_str(order_list[ord].order_id.exp_date)
                    result['created_at'] = j.created_at
                    result['modified_at'] = j.modified_at
        result_list.append(result)
    #####################################################################

    return sch_date_from.strftime("%Y-%m-%d"), sch_date_to.strftime("%Y-%m-%d"), result_list

# 설비정보수정
def fac_list_edit(request):
    if request.method == 'POST':
        request = json.loads(request.body)

    facility_name = request['facility_name']
    facility_id = request['facility_id']

    company_list = Facility.objects.get(facility_id=facility_id)
    company_list.facility_name = facility_name

    company_list.save();

    return JsonResponse({"message": 'success'})


def delete(request):
    if request.method == 'POST':
        request = json.loads(request.body)
        id = request['id']
        if request['type'] == 'product':
            prod_id = Product.objects.get(prod_id=id)
            company = get_object_or_404(Product, pk=prod_id.idx)
        else:
            company = get_object_or_404(Facility, pk=id)
        company.delete()
        return HttpResponse(status=200)

# 제품정보등록 company product register HTML
def comp_product_regist(request):
    template_name = 'company/comp_product_regist.html'
    comp_list = Facility.objects.all()
    date = datetime.datetime.today() - timedelta(days=3)
    date = {
        "comp_list": comp_list,
        'dateFrom': date.strftime("%Y-%m-%d"),
        'path': '제품정보 / 제품등록'
    }

    return render(request, template_name, date)

# 제품정보검색 company product view HTML
def comp_product_view(request):
    template_name = 'company/comp_product_list.html'
    user = auth.get_user(request)
    group = request.user.groups.values_list('name', flat=True).first()
    if group == 'customer':
        comp_list = Product.objects.all()
    else:
        comp_list = Product.objects.filter(comp_id=request.user.groups.values('id')[0]['id'])
    for i in comp_list:
        i.cost = money_count(i.cost)
    date = datetime.datetime.today() - timedelta(days=3)
    date = {
        "comp_list": comp_list,
        'dateFrom': date.strftime("%Y-%m-%d"),
        'path': '제품정보 / 제품검색'
    }
    return render(request, template_name, date)

jobshop/frontend/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
import datetime, json
from datetime import timedelta

# Create your views here.
def index(request):
    template_name = 'main/index.html'

    dateFrom, dateTo = get_dates(request)

    context = {
        'dateFrom': dateFrom,
        'dateTo': dateTo,
        'path': '대시보드',
        'selected': 'ordermanagement'
    }
    return render(request, template_name, context)

def get_dates(request):
    date = datetime.datetime.today() - timedelta(days=3)

    if 'dateFrom' in request.GET:
        date_from = datetime.datetime.strptime(request.GET['dateFrom'], "%Y-%m-%d")
        date_to = datetime.datetime.strptime(request.GET['dateTo'], "%Y-%m-%d")
    else:
        date_from = date
        date_to = datetime.datetime.today()

    return date_from.strftime("%Y-%m-%d"), date_to.strftime("%Y-%m-%d")
# board
def board(request):
    return render(request, 'main/board.html')

# login
# def login(request):
#     return render(request, 'main/login.html')

# logout
def logout(request):
    return render(request, 'common/logout.html')

# nav 메뉴
def nav(request):
    return render(request, 'common/nav.html')

# topbar - 검색 바
def topbar(request):
    return render(request, 'common/topbar.html')

# footer
def footer(request):
    return render(request, 'common/footer.html')

# compregist
def company(request):
    return render(request, 'company/comp_regist.html')

# compregist
def test(request):
    return render(request, 'test.html')

jobshop/frontend/templates/company/comp_regist.html
{% extends "common/header.html" %}
{% block content %}
<style>
    .dataTables_wrapper .dataTables_filter {display:none;}
    .pagination {display:none;}
    .dataTables_info {display:none;}
    input {border:none; width:100%; color:#858796;}
</style>
<div class="col-md-12 col-lg-12">
    <div class="card">
      <div class="card-header" style="margin-left:73%;">
            <a href="#" class="btn btn-info btn-icon-split modal-upload-btn">
                <span class="icon text-white-50">
                    <i class="fas fa-check"></i>
                </span>
                <span class="text">설비개별업로드</span>
            </a>
            <a href="#" class="btn btn-success btn-success-csv btn-icon-split upload-btn" style="margin-left:5%;">
                <span class="icon text-white-50">
                    <i class="fas fa-check"></i>
                </span>
                <span class="text">.csv 업로드</span>
            </a>
      </div>
      <div class="card-table table-responsive">
        <form id="orderForm" method="POST" action="{% url 'company:csvCreate' %}">
            <table class="table table-vcenter">
                <thead>
                    <tr>
                      <th>번호</th>
                      <th>설비명</th>
                      <th style="text-align:center;">관리</th>
                    </tr>
                </thead>
                <tbody class="tbody-data">

                </tbody>
            </table>
            <div class="dropdown dropdown-btn no-arrow" style="text-align:right;">
                <button type="submit" value="OrderList" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                    <i class="fas fa-upload fa-sm text-white-50"></i> 설비업로드
                </button>
            </div>
        </form>
      </div>
    </div>
</div>



<!--<div class="card shadow mb-4">-->
<!--    <div class="card-body">-->
<!--        <div class="pknu-table-responsive">-->
<!--            <div class="no-arrow no-arrow-btn" style="position:absolute; right:1.2%; z-index:100;">-->
<!--                <a href="#" class="btn btn-info btn-icon-split modal-upload-btn">-->
<!--                    <span class="icon text-white-50">-->
<!--                        <i class="fas fa-check"></i>-->
<!--                    </span>-->
<!--                    <span class="text">설비개별업로드</span>-->
<!--                </a>-->
<!--                <a href="#" class="btn btn-success btn-success-csv btn-icon-split upload-btn">-->
<!--                    <span class="icon text-white-50">-->
<!--                        <i class="fas fa-check"></i>-->
<!--                    </span>-->
<!--                    <span class="text">.csv 업로드</span>-->
<!--                </a>-->
<!--            </div>-->
<!--            <form id="orderForm" method="POST" action="{% url 'company:csvCreate' %}">-->
<!--                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">-->
<!--                    <thead>-->
<!--                        <tr>-->
<!--                            <th>번호</th>-->
<!--                            <th>설비명</th>-->
<!--                            <th style="text-align:center;">관리</th>-->
<!--                        </tr>-->
<!--                    </thead>-->
<!--                    <tbody class="tbody-data">-->

<!--                    </tbody>-->
<!--                </table>-->
<!--                <div class="dropdown dropdown-btn no-arrow" style="text-align:right;">-->
<!--                    <button type="submit" value="OrderList" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">-->
<!--                        <i class="fas fa-upload fa-sm text-white-50"></i> 설비업로드-->
<!--                    </button>-->
<!--                </div>-->
<!--            </form>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

<!-- OrderUploadModal -->
<div class="modal fade" id="uploadModal" role="dialog" aria-labelledby="uploadModal" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog2" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">설비 등록</h4>
                <button class="close" type="button" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
            </div>
            <div class="modal-body">
                <div class="row pknu-modal-row">
                    <div class="col-md-3"><label class="pt-2" style="font-size:0.95rem;">설비명</label></div>
                    <div class="col-lg-6">
                        <p class="modal-p">※ 호기 번호만 입력해 주세요.<p/><br/>
                        <input class="form-control text-center" type="text" name="compname" id="compname" />
                    </div>
                </div>
            </div>
            <div class="modal-footer" id="modal-footer">
                <button type="button" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm" data-bs-dismiss="modal">
                    <i class="far fa-window-close fa-sm text-white-50"></i> 취소
                </button>
                <a class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" id="modal-upload">
                    <i class="fas fa-upload fa-sm text-white-50"></i> 설비정보업로드
                </a>
            </div>
        </div>
    </div>
</div>
<!-- OrderUploadModal -->

<!-- Modal-->
<div class="modal fade" id="excelUploadModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" style="padding-right: 17px;" aria-modal="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <!--modal header-->
            <div class="modal-header">
                <h5 class="modal-title" id="">설비 정보 문서 등록</h5>
                <button class="close" type="button" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <!--modal header-->
            <!--modal body-->
            <div class="modal-body">
                <div class="modal-body">
                    <div class="md-form mb-3">
                        <div class="col-auto">
                            <form action="#" class="dropzone" name="compDocDropzone" id="compDocDropzone" enctype="multipart/form-data">
                                <div class="fallback">
                                    <input type="file" name="file" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!--modal body-->
            <!--modal footer-->
            <div class="modal-footer">
                <a href="{% url 'company:company.comp_csv_download_blank' %}" class="btn btn-info btn-icon-split upload-btn">
                    <span class="icon text-white-50">
                        <i class="fas fa-check"></i>
                    </span>
                    <span class="text">설비문서업로드양식다운로드</span>
                </a>
                <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">취소</button>
                <button type="button" class="btn btn-primary" id="fileReadBtn">업로드</button>
            </div>
            <!--modal footer-->
        </div>
    </div>
</div>
<!-- Modal-->
<!--게시판 관련 js-->
<!-- Page level plugins -->
<script src="/static/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/static/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script src="/static/js/dropzone/dropzone.min.js"></script>
<!-- Page level custom scripts -->
<script src="/static/js/demo/datatables-demo.js"></script>

<script>
    Dropzone.autoDiscover = false; // dropzone 초기화
    function hasExtension(fileName, exts) {
        return (new RegExp('(' + exts.join('|').replace(/\./g, '\\.') + ')$')).test(fileName);
    }
    var fileName = "";
    $(function(){
        $(".dropdown-btn").css('display', 'none');

        // csv 업로드
        var _url = "{% url 'company:company.comp_read_csv' %}";

        var formData = new FormData();
        //dropzone에 파일등록
        var dropzone = new Dropzone("#compDocDropzone", {
            url: "{% url 'company:upload' %}",
            addRemoveLinks: true,
            maxFiles: 1,
            init: function(e) {
                // 파일 업로드 성공 시
                this.on('success', function(file) {
                    formData.append("file", dropzone.getAcceptedFiles()[0]);
                    fileName = file.name;
                    //확장자 체크(작업장별 다름)
                    if(!hasExtension(fileName, ['csv'])){
                        Swal.fire({
                          icon: 'error',
                          title: '파일 형식 오류',
                          text: '.csv 파일을 업로드 해 주세요.',
                        });
                        return false;
                    }
                });

            }
        });
        // 설비 정보 업로드 버튼
        $('.modal-upload-btn').on('click', function(){
            $('#uploadModal').modal({backdrop: 'static', keyboard: false})
            $("#uploadModal").modal("show");
        });
        // .csv 업로드 버튼
        $('.upload-btn').on('click', function(){
            $('#excelUploadModal').modal({backdrop: 'static', keyboard: false})
            $("#excelUploadModal").modal("show");
        });

        // 설비 정보 업로드 버튼 설비정보업로드 버튼 클릭 이벤트
        $("#modal-upload").on("click", function(){
            var obj = new Object();
            obj.comp_name = $('#compname').val();

            $.ajax({
                url: "{% url 'company:company.comp_update_modal' %}",
                data : JSON.stringify(obj),
                type:'json',
                contentType: 'application/json',
                method: "POST",
                success: function(data){
                    $(location).attr('href', "{% url 'company:company.list' %}")
                }
            })
        });

        $("#fileReadBtn").on("click", function(e){
            $.ajax({
                url: _url,
                method:'POST',
                contentType: false,
                processData: false,
                data: formData,
                success: function(result){
                    $(".dropdown-btn").css('display', 'block');
                    $(".upload-btn").css('display', 'none');
                    var innerHTML;
                    var count = 0;
                    for(var i=0; i<result.length; i++){
                        count = count + 1;
                        innerHTML += '<tr>' +
                            '<td>' + count + '</td>' +
                            '<td><input name="facility_name" value="' + result[i].facility_name + '"/></td>' +
                            '<td style="text-align:center;">' +
                                '<a href="#" id="delete_'+ count +'" onclick="deletedOrder(\'' + result[i].prod_name + '\',\'' + result[i].density + '\')"><i class="fas fa-trash-alt"></i></a>' +
                            '</td>' +
                        '</tr>';
                    }
                    $('.tbody-data').html(innerHTML);
                    if(result.message == 'error'){
                        Swal.fire({
                          icon: 'error',
                          title: '파일 형식 오류',
                          text: '데이터 항목을 형식에 맞춘 후 업로드 해 주세요.',
                          footer: '<a href="">형식 다운로드</a>'
                        });
                        return false;
                    } else {
                        $('#excelUploadModal').modal('hide');
                    }
                },
                error: function(error){
                    console.log(error);
                    // $('#css-loader').removeClass("is-active");
                }
            });
        });

        $('#form').attr('action',"{% url 'order:order.csvCreate' %}").submit();
    });
    function deletedOrder(name, amount){
        var selectdata = new Object();
        selectdata.name = name;
        selectdata.amount = amount;
        selectdata.fileName = fileName;
        Swal.fire({
          icon: 'error',
          title: '삭제하시겠습니까?',
          showCancelButton: true,
          text: ''
        }).then(function(){
            $.ajax({
                url: "{% url 'order:order.order_delete_read_csv' %}",
                data : JSON.stringify(selectdata),
                type:'json',
                contentType: 'application/json',
                method: "POST",
                success: function(data){
                    $('.tbody-data').html('');
                    $(".dropdown-btn").css('display', 'block');
                    var innerHTML;
                    var count = 0;
                    for(var i=0; i<data.length; i++){
                        count = count + 1;
                        innerHTML += '<tr>' +
                            '<td>' + count + '</td>' +
                            '<td><input name="facility_name" value="' + data[i].facility_name + '"/></td>' +
                            '<td style="text-align:center;">' +
                                '<a href="#" id="delete_'+ count +'" onclick="deletedOrder(\'' + data[i].cust_name + '\',\'' + data[i].amount + '\')"><i class="fas fa-trash-alt"></i></a>' +
                            '</td>' +
                        '</tr>';
                    }
                    $('.tbody-data').html(innerHTML);
                },
                error: function(error){
                    console.log(error)
                }
            });
        });
        return false;
    }
</script>
{% endblock %}