jobshop/board/urls.py
# board/urls.py

from django.urls import path

from .views import ArticleList, ArticleDetail, ArticleDelete, ArticleCreate, ArticleUpdate

urlpatterns = [
    path('', ArticleList.as_view(), name='index'),
    path('create/', ArticleCreate.as_view(), name='create'),
    path('<int:pk>/', ArticleDetail.as_view(), name='detail'),
    path('<int:pk>/update/', ArticleUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', ArticleDelete.as_view(), name='delete'),
]

jobshop/company/urls.py
# company/urls.py

from django.urls import path

from .views import *

app_name = 'company'
urlpatterns = [
    path('', home, name='company.index'),
    path('product/regist/', comp_product_regist, name='company.product'),
    path('product/search/', comp_product_view, name='company.product.view'),
    path('product/list/all/', product_search, name='company.product_search'),
    path('product/list/edit/', prod_list_edit, name='company.prod_list_edit'),

    path('facility/list/', comp_production_view, name='company.facility'),
    path('facility/list/edit/', fac_list_edit, name='company.fac_list_edit'),
    path('facility/list/all/', comp_facility_all, name='company.comp_facility_all'),
    path('csv/facility/download/', comp_facility_csv_download, name='company.comp_facility_csv_download'),
    path('info/list/', comp_list_view, name='company.list'),
    path('excel/create/', comp_update_excel, name='create'),
    path('csv/create/', comp_update_csv, name='csvCreate'),
    path('modal/create/', comp_update_modal, name='company.comp_update_modal'),

    path('csv/comp/read/', comp_read_csv, name='company.comp_read_csv'),
    path('csv/comp/download/blank/', comp_csv_download_blank, name='company.comp_csv_download_blank'),
    path('csv/comp/download/', comp_csv_download, name='company.comp_csv_download'),
    path('avail/facility/', comp_avail_facility, name='company.comp_avail_facility'),
    path('csv/production/download/', comp_production_csv_download, name='company.comp_production_csv_download'),

    path('csv/prod/read/', prod_read_csv, name='company.prod_read_csv'),
    path('csv/prod/upload/', comp_prod_update_csv, name='company.comp_prod_update_csv'),
    path('csv/prod/download/', prod_csv_download, name='company.prod_csv_download'),
    path('csv/prod/download/blank/', prod_csv_download_blank, name='company.prod_csv_download_blank'),

    path('modal/prod/upload/', comp_prod_update_modal, name='company.comp_prod_update_modal'),
    path('csv/upload/', upload_file, name='upload'),
    path('delete/', delete, name='delete'),
]

jobshop/jobshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from frontend import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('logout/', views.logout, name='logout'),
    path('board/', views.board),
    path('test/', views.test),
    path('nav/', views.nav),
    path('footer/', views.footer),
    path('topbar/', views.topbar),
    path('board/', include('board.urls'), name='board'),
    path('company/', include('company.urls'), name='company'),
    path('schedule/', include('schedule.urls'), name='schedule'),
    path('common/', include('common.urls')),
    path('recommend/', include('recommend.urls')),
    path('order/', include('order.urls'), name='order'),
]
# 파일 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

jobshop/recommend/urls.py
# order/urls.py

from django.urls import path

from .views import *
app_name = 'recommend'
urlpatterns = [
    path('', home, name='recommend.home'),
]

jobshop/frontend/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
import datetime, json
from datetime import timedelta

# Create your views here.
def index(request):
    template_name = 'main/index.html'

    dateFrom, dateTo = get_dates(request)

    context = {
        'dateFrom': dateFrom,
        'dateTo': dateTo,
        'path': '대시보드',
        'selected': 'ordermanagement'
    }
    return render(request, template_name, context)

def get_dates(request):
    date = datetime.datetime.today() - timedelta(days=3)

    if 'dateFrom' in request.GET:
        date_from = datetime.datetime.strptime(request.GET['dateFrom'], "%Y-%m-%d")
        date_to = datetime.datetime.strptime(request.GET['dateTo'], "%Y-%m-%d")
    else:
        date_from = date
        date_to = datetime.datetime.today()

    return date_from.strftime("%Y-%m-%d"), date_to.strftime("%Y-%m-%d")
# board
def board(request):
    return render(request, 'main/board.html')

# login
# def login(request):
#     return render(request, 'main/login.html')

# logout
def logout(request):
    return render(request, 'common/logout.html')

# nav 메뉴
def nav(request):
    return render(request, 'common/nav.html')

# topbar - 검색 바
def topbar(request):
    return render(request, 'common/topbar.html')

# footer
def footer(request):
    return render(request, 'common/footer.html')

# compregist
def company(request):
    return render(request, 'company/comp_regist.html')

# compregist
def test(request):
    return render(request, 'test.html')

jobshop/recommend/views.py
#-*- coding: utf-8 -*-
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User, Group
from django.contrib import auth
from django.utils.encoding import smart_str
from django.db.models import Max
from django.template import loader
from rest_framework import serializers
from company.models import Schedule, Information, Product, Facility
from common.views import id_generate, date_str, date_remove, money_count
from company.models import *
from datetime import timedelta
import datetime, json, csv, math
import pandas as pd
from urllib.parse import quote

# 소재 추천 목록 recommend list HTML
def home(request):
    template_name = 'recommend/recommend_list.html'
    recommends = recommend_list(request)
    context = {
        'path': '소재추천 / 추천소재검색',
        'recommends': recommends,
        'selected': 'recommendlist'
    }
    return render(request, template_name, context)

def recommend_list(request):
    recomm_select = Product.objects.filter(recommend_yn='Y')
    recomm_list = []
    for i in recomm_select:
        result_dict = {}
        result_dict['prod_id'] = i.prod_id
        result_dict['comp_id'] = i.comp_id_id
        result_dict['comp_name'] = i.comp_id.comp_name
        result_dict['prod_name'] = i.prod_name
        result_dict['density'] = i.density
        result_dict['rpm'] = i.rpm
        result_dict['daily_prod_rate'] = i.daily_prod_rate
        result_dict['cost'] = i.cost
        result_dict['image'] = i.image
        recomm_list.append(result_dict)

    return recomm_list

jobshop/frontend/templates/recommend/recommend_list.html
{% extends "common/header.html" %}
{% block content %}

<!-- Page Heading -->
<div class="row">
    {% for comp in recommends %}
    <div class="col-xl-2 col-lg-6 col-sm-6">
        <div class="card">
            <div class="card-body">
                <div class="new-arrival-product">
                    <div class="new-arrivals-img-contnent">
                        <img class="img-fluid" src="/media/{{comp.image}}" alt="">
                    </div>
                    <div class="new-arrival-content text-center mt-3">
                        <h4> <img src="https://img.icons8.com/external-flat-icons-pack-pongsakorn-tan/64/000000/external-company-labor-day-flat-icons-pack-pongsakorn-tan.png"
                        style="width:13%; margin-right:0.3rem;"/> {{comp.comp_name}}</h4>
                        <span class="price"> <h4>제품명 :</h4> {{comp.prod_name}}</span>
                        <h4>{{comp.cost}} 원</h4>

                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

<!--게시판 관련 js-->
<!-- Page level plugins -->
<script src="/static/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/static/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<!-- Page level custom scripts -->
<script src="/static/js/demo/datatables-demo.js"></script>
<!-- sweetalert 설치 후 사용가능
     $ npm install sweetalert2 -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<!--게시판 관련 js-->
<script>
$(function(){
    const today = moment();
    // 검색 날짜 init
    flatpickr("#dateTo", {
           locale: Flatpickr.l10ns.ko,
           enableTime: false,
           dateFormat: "Y-m-d",
           disableMobile: true,
           defaultDate: $('#dateTo').val()
           // defaultDate: [today.format('YYYY-MM-DD')]
    });
    flatpickr("#dateFrom", {
           locale: Flatpickr.l10ns.ko,
           enableTime: false,
           dateFormat: "Y-m-d",
           disableMobile: true,
           defaultDate: $('#dateFrom').val()
    });
    // 수정
    $('.editContBtn').on('click', function(){
        $('#editModal').modal("show");
    });
    // 삭제
    var selectdata = new Object;
    $('.deleteBtn').on('click', function(e){
        var str = e.currentTarget.id.split('_');
        selectdata.id = str[1];
        selectdata.type = 'product';
        Swal.fire({
          icon: 'error',
          title: '삭제하시겠습니까?',
          showCancelButton: true,
          text: ''
        }).then(function(){
            $.ajax({
                url: "{% url 'company:delete' %}",
                data : JSON.stringify(selectdata),
                type:'json',
                contentType: 'application/json',
                method: "POST",
                success: function(data){
                    location.reload();
                },
                error: function(error){
                    console.log(error)
                }
            });
        });
        return false;
    });

});
</script>
{% endblock %}