jobshop/board/urls.py
# board/urls.py

from django.urls import path

from .views import ArticleList, ArticleDetail, ArticleDelete, ArticleCreate, ArticleUpdate

urlpatterns = [
    path('', ArticleList.as_view(), name='index'),
    path('create/', ArticleCreate.as_view(), name='create'),
    path('<int:pk>/', ArticleDetail.as_view(), name='detail'),
    path('<int:pk>/update/', ArticleUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', ArticleDelete.as_view(), name='delete'),
]

jobshop/jobshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from frontend import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('logout/', views.logout, name='logout'),
    path('board/', views.board),
    path('test/', views.test),
    path('nav/', views.nav),
    path('footer/', views.footer),
    path('topbar/', views.topbar),
    path('board/', include('board.urls'), name='board'),
    path('company/', include('company.urls'), name='company'),
    path('schedule/', include('schedule.urls'), name='schedule'),
    path('common/', include('common.urls')),
    path('recommend/', include('recommend.urls')),
    path('order/', include('order.urls'), name='order'),
]
# 파일 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

jobshop/schedule/urls.py
# schedule/urls.py

from django.urls import path

from .views import *
app_name = 'schedule'
urlpatterns = [
    path('', home, name='schedule.index'),
    path('history/', history, name='schedule.history'),
    path('confirmed/', sch_confirmed, name='schedule.sch_confirmed'),
    path('confirmed/monthly/', monthly_confirmed_order, name='schedule.monthly_confirmed_order'),
    path('history/chart/<str:id>/<str:schDate>/', history_chart, name='schedule.history_chart'),
    path('history/graph/chart/', draw_history_chart, name='draw_history_chart'),
    path('graph/csv/generate/', generate_data, name='generate_data'),
    path('graph/draw/', draw_graph, name='draw_graph'),
    path('avail/comp/', available_comp, name='available_comp'),
    path('test/data/', test_data, name='test_data'),
    path('fixed/order/', fixed_order, name='fixed_order'),
    path('confirmed/order/', confirmed_order, name='confirmed_order'),
    path('delete/order/', delete_order, name='delete_order'),
    path('schedule/history/', schedule_history, name='schedule_history'),
    # path('create/', ArticleCreate.as_view(), name='create'),
    # path('<int:pk>/', ArticleDetail.as_view(), name='detail'),
    # path('<int:pk>/update/', ArticleUpdate.as_view(), name='update'),
    # path('<int:pk>/delete/', ArticleDelete.as_view(), name='delete'),
]

jobshop/frontend/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
import datetime, json
from datetime import timedelta

# Create your views here.
def index(request):
    template_name = 'main/index.html'

    dateFrom, dateTo = get_dates(request)

    context = {
        'dateFrom': dateFrom,
        'dateTo': dateTo,
        'path': '대시보드',
        'selected': 'ordermanagement'
    }
    return render(request, template_name, context)

def get_dates(request):
    date = datetime.datetime.today() - timedelta(days=3)

    if 'dateFrom' in request.GET:
        date_from = datetime.datetime.strptime(request.GET['dateFrom'], "%Y-%m-%d")
        date_to = datetime.datetime.strptime(request.GET['dateTo'], "%Y-%m-%d")
    else:
        date_from = date
        date_to = datetime.datetime.today()

    return date_from.strftime("%Y-%m-%d"), date_to.strftime("%Y-%m-%d")
# board
def board(request):
    return render(request, 'main/board.html')

# login
# def login(request):
#     return render(request, 'main/login.html')

# logout
def logout(request):
    return render(request, 'common/logout.html')

# nav 메뉴
def nav(request):
    return render(request, 'common/nav.html')

# topbar - 검색 바
def topbar(request):
    return render(request, 'common/topbar.html')

# footer
def footer(request):
    return render(request, 'common/footer.html')

# compregist
def company(request):
    return render(request, 'company/comp_regist.html')

# compregist
def test(request):
    return render(request, 'test.html')

jobshop/schedule/views.py
from django.shortcuts import render
from django.db.models import Max
from django.db.models.aggregates import Count
from django.contrib.auth.models import User, Group
from django.http import JsonResponse
from django.http.response import HttpResponse
from .sslstm import sslstm
from common.views import id_generate, date_str, calc_date_str, comma_str, date_remove
from company.models import *
from order.models import *
import pandas as pd
import json, csv, os, datetime, calendar, random
from datetime import timedelta
from calendar import monthrange
from bson import json_util
from random import randint

now = datetime.datetime.now()
# 스케쥴링실행 Execute Schedule HTML
def home(request):
    date = datetime.datetime.today() - timedelta(days=3)
    date = {
        'dateFrom': date.strftime("%Y-%m-%d"),
        'path': '스케쥴링 / 스케쥴링실행'
    }
    return render(request, 'schedule/schedule.html', date)

# 스케쥴링이력 Schedule history HTML
def history(request):
    date = datetime.datetime.today() - timedelta(days=3)
    if 'dateFrom' in request.GET:
        sch_date_from = datetime.datetime.strptime(request.GET['dateFrom'], "%Y-%m-%d")
        sch_date_to = datetime.datetime.strptime(request.GET['dateTo'], "%Y-%m-%d")

        date_from = request.GET['dateFrom'].replace('-', '')
        date_to = request.GET['dateTo'].replace('-', '')
        schedule_list = Schedule.objects.raw(
            " SELECT sch_id, SUBSTRING(sch_id, 4, 8) as exe_date, max(COUNT) as max_count " +
            " FROM company_schedule " +
            " WHERE SUBSTRING(sch_id, 4, 8) >= '" + date_from + "' AND "
                    "SUBSTRING(sch_id, 4, 8) <= '" + date_to + "'" +
            ' GROUP BY STR_TO_DATE(created_at, "%%Y-%%m-%%d")')
    else:
        sch_date_from = date
        sch_date_to = datetime.datetime.today()
        schedule_list = Schedule.objects.raw(
            "SELECT *, SUBSTRING(sch_id, 4, 8) as exe_date, max(COUNT) as max_count " +
            "FROM company_schedule " +
            "WHERE SUBSTRING(sch_id, 4, 8) >= '" + date.strftime("%Y%m%d") + "' AND "
            "SUBSTRING(sch_id, 4, 8) <= '" + datetime.datetime.today().strftime( "%Y%m%d") + "'" +
            ' GROUP BY STR_TO_DATE(created_at, "%%Y-%%m-%%d")')

    sch_list = []
    order_id = ''
    for sch in schedule_list:
        sch_dict = {}
        sch_dict['max_count'] = sch.max_count
        sch_dict['exe_date'] = date_str(sch.exe_date)
        sch_dict['work_end_date'] = date_str(sch.work_end_date)
        sch_dict['date_from'] = sch_date_from.strftime("%Y-%m-%d")
        sch_dict['date_to'] = sch_date_to.strftime("%Y-%m-%d")
        order_list = OrderList.objects.filter(prod_id=sch.prod_id)
        if len(order_list) == 0:
            continue;
        order_id = date_str(sch.exe_date)

        for i in order_list:
            sch_dict['sch_date'] = date_str(i.sch_date)

        sch_dict['orderid'] = order_id
        sch_list.append(sch_dict)

    date = {
        'dateFrom': sch_date_from.strftime("%Y-%m-%d"),
        'dateTo': sch_date_to.strftime("%Y-%m-%d"),
        'path': '스케쥴링 / 스케쥴링이력',
        'sch_list' : sch_list
    }
    return render(request, 'schedule/sch_history.html', date)

# 스케쥴링이력 간트차트 Schedule history in Gantt Chart HTML
def history_chart(request, id, schDate):
    date = datetime.datetime.today() - timedelta(days=3)

    date = {
        'dateFrom': date.strftime("%Y-%m-%d"),
        'id' : id,
        'schDate' : schDate,
        'path': '스케쥴링 / 스케쥴링이력',
    }
    return render(request, 'schedule/sch_history_chart.html', date)

# 스케쥴링이력 간트차트 그리기
def draw_history_chart(request):

    for i in request.GET:
        request = json.loads(i)

    id = request['orderId'] # 스케줄일자
    schDate = request['schDate'] # 주문일자

    sch_list, count = schedule_list(id, schDate)

    result = {}
    result_list = []
    final_list = []

    for cnt in range(int(count)+1):
        result['max_count'] = int(cnt)+1
        for sch in sch_list:
            product = Product.objects.filter(prod_id=sch.prod_id)[0]
            if sch.count == int(cnt)+1:
                result_dict = {}
                result_dict['facility_id'] = sch.facility_id.facility_name
                result_dict['prod_name'] = product.prod_name
                result_dict['order_id_num'] = sch.order_id_num
                result_dict['count'] = sch.count
                result_dict['sch_color'] = sch.sch_color
                result_dict['x_axis_1'] = sch.x_axis_1
                result_dict['x_axis_2'] = sch.x_axis_2
                result_dict['y_axis_1'] = sch.y_axis_1
                result_dict['work_str_date'] = date_str(sch.work_str_date)
                result_dict['work_end_date'] = date_str(sch.work_end_date)
                result_list.append(result_dict)
        result['chart_draw'] = result_list
    final_list.append(result)

    def json_default(value):
        if isinstance(value, datetime.datetime):
            return value.strftime('%Y-%m-%d')
        raise TypeError('not JSON serializable')

    return HttpResponse(json.dumps(final_list, default=json_default, ensure_ascii=False), content_type="application/json")

# 확정 스케쥴 Fixed Schedule HTML
def sch_confirmed(request):
    date = datetime.datetime.today()
    date = date.strftime("%Y%m%d")
    year = date[0:4]
    month = date[4:6]

    lastday = calendar.monthrange(int(year), int(month))[1]
    final_result = OrderSchedule.objects.filter(sch_id__work_end_date__gte=date, use_yn='Y')
    available_list = []
    for i in final_result:
        available_dict = {}
        available_dict['work_str_date'] = date_str(i.sch_id.work_str_date)
        available_dict['work_end_date'] = date_str(i.sch_id.work_end_date)
        available_dict['order_id'] = i.order_id_id
        orderlist = OrderList.objects.get(order_id=i.order_id_id)
        available_dict['sch_date'] = date_str(orderlist.sch_date)
        available_dict['sch_id'] = i.sch_id
        available_list.append(available_dict)

    date = {
        'order_list': available_list,
        'path': '스케쥴링 / 확정스케쥴조회'
    }
    return render(request, 'schedule/sch_confirmed.html', date)

def schedule_list(id, schDate):

    date_from = id.replace('-', '')

    schedule_list = Schedule.objects.raw(
        "SELECT * " +
        "FROM company_schedule " +
        "WHERE SUBSTRING(sch_id, 4, 8) = '" + date_from + "' ")

    count = Schedule.objects.raw(
        ' SELECT sch_id, MAX(COUNT) as count ' +
        ' FROM company_schedule' +
        ' WHERE SUBSTRING(sch_id, 4, 8) = "' + date_from + '"')
    sch_list = []
    for i in schedule_list:
        sch_list.append(i)
    for j in count:
        count = j.count

    return sch_list, count


# 수락한 오더 리스트 조회 (월별)
def monthly_confirmed_order(request):
    date = datetime.datetime.today().strftime("%Y%m")
    for i in request.GET:
        request = json.loads(i)
    available_list = []

    if request['str_year'] != None:
        str_year = request['str_year']
        str_month = request['str_month']
        end_year = request['end_year']
        end_month = request['end_month']

        final_result = OrderSchedule.objects.filter(sch_id__work_end_date__lte=str(end_year) + str(end_month) + '31', use_yn='Y')
    else:
        year = date[0:4]
        month = date[4:6]
        lastday = calendar.monthrange(int(year), int(month))[1]
        final_result = OrderSchedule.objects.filter(sch_id__work_str_date__gte=date + '01').filter(
            sch_id__work_end_date__lte=date + str(lastday), use_yn='Y')

    for i in final_result:
        available_dict = {}
        available_dict['work_str_date'] = i.sch_id.work_str_date
        available_dict['work_end_date'] = i.sch_id.work_end_date
        available_dict['order_id'] = i.order_id_id
        available_dict['sch_id'] = i.sch_id_id
        available_list.append(available_dict)

    def json_default(value):
        if isinstance(value, datetime.datetime):
            return value.strftime('%Y-%m-%d')
        raise TypeError('not JSON serializable')
    # return JsonResponse(list(available_list), safe=False)
    return HttpResponse(json.dumps(available_list, default=json_default, ensure_ascii=False), content_type="application/json")

# draw Gantt Chart data
def draw_graph(request):
    count = Schedule.objects.filter(comp_id=request.user.groups.values('id')[0]['id'],
                                    created_at__year=now.year, created_at__month=now.month, created_at__day=now.day)
    count = count.aggregate(Max('count'))
    print(now.year, ' / ', now.month, ' / ', now.day+1)
    for i in Group.objects.all():
        for j in Group.objects.filter(name=i).values():
            schedule_list = Schedule.objects.filter(count=count['count__max'],
                                    created_at__year=now.year, created_at__month=now.month, created_at__day=now.day)
            schedule_list = list(schedule_list.values())
    for i in range(len(schedule_list)):
        fac_name = Facility.objects.get(facility_id=schedule_list[i]['facility_id_id'])
        schedule_list[i]['work_str_date'] = date_str(schedule_list[i]['work_str_date'])
        schedule_list[i]['work_end_date'] = date_str(schedule_list[i]['work_end_date'])
        schedule_list[i]['y_axis_1'] = fac_name.facility_name
        product = Product.objects.get(prod_id=schedule_list[i]['prod_id'])
        schedule_list[i]['prod_name'] = product.prod_name


    def json_default(value):
        if isinstance(value, datetime.datetime):
            return value.strftime('%Y-%m-%d')
        raise TypeError('not JSON serializable')

    print(json.dumps(schedule_list, default=json_default))
    return HttpResponse(json.dumps(schedule_list, default=json_default))

# JSSP 스케쥴링 실행
# x, y 축 저장 Save x, y axis into Database
# def generate_data(request):
#     # 회사 아이디를 얻기 위한 유저 정보
#     user_id = request.user.groups.values('id')[0]['id']
#     data = open("./schedule/dytech/new_coming.csv", "w", newline="", encoding="UTF-8")

jobshop/frontend/templates/schedule/sch_confirmed.html
{% extends "common/header.html" %}
{% block content %}
<div class="row">
    <div class="col-xl-7 col-lg-5">
        <div class="card shadow mb-4">
            <div id='calendar'></div>
        </div>
    </div>
    <div class="col-lg-5">
        <!-- Circle Buttons -->
        <div class="card shadow mb-4">
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">금일 작업 리스트</h6>

            </div>
            <div class="card-body" id="order_list">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">번호</th>
                            <th scope="col">스케쥴실행일자</th>
                            <th scope="col">작업기한요청일</th>
                            <th scope="col">오더일자</th>
                            <th scope="col">오더번호</th>
                        </tr>
                    </thead>
                    <tbody class="order_body">
                        {% for order in order_list %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{order.work_str_date}}</td>
                            <td>{{order.work_end_date}}</td>
                            <td>{{order.sch_date}}</td>
                            <td>{{order.order_id}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- 처리 가능 리스트 히스토리 -->

    </div>
</div>

<!-- **************************  modal start  ************************** -->
<div class="modal fade" id="activationSettingModal"tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">JSS Setting</h4>
                    <button class="close" type="button" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
            <div class="modal-body">
                <div class="row pknu-modal-row" >
                    <div class="col-md-3"><label for="schExeDate" class="pt-2">스케쥴일자</label></div>
                    <div class="col-md-6">
                         <input type="text" class="form-control" id="schExeDate" aria-describedby="emailHelp" placeholder="" value="" readonly="readonly" />
                    </div>
                </div>
                <div class="row pknu-modal-row">
                    <div class="col-md-3"><label for="workStartDate" class="pt-2">작업시작일</label></div>
                    <div class="col-md-6">
                         <input type="text" class="form-control" id="workStartDate" aria-describedby="emailHelp" placeholder="" value="" readonly="readonly" />
                    </div>
                </div>
                <div class="row pknu-modal-row">
                    <div class="col-md-3"><label for="workEndDate" class="pt-2">작업기한</label></div>
                    <div class="col-md-6">
                         <input type="text" class="form-control" id="workEndDate" aria-describedby="emailHelp" placeholder="" value="" readonly="readonly" />
                    </div>
                </div>
                <div class="row pknu-modal-row">
                    <div class="col-md-3"><label for="orderId" class="pt-2" style="font-size:0.95rem;">오더번호</label></div>
                    <div class="col-lg-6" >
                         <input class="form-control text-center" type="text" name="dateFrom" id="orderId" readonly="readonly"/>
                    </div>
                </div>
            </div>
            <div class="modal-footer" id="htfooter">
                <button type="button" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm" data-bs-dismiss="modal">
                    <i class="far fa-window-close fa-sm text-white-50"></i> 취소
                </button>
            </div>
        </div>
    </div>
</div>
<!-- **************************  modal end  ************************** -->

<script>
function dateformat(value){
    var year = value.substring(0,4);
    var month = value.substring(4,6);
    var day = value.substring(6,8);
    var date = year + '-' + month + '-' + day;
    return date;
}
$(function(){
    const today = moment();
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
        plugins: [ 'interaction', 'dayGrid' ],
        defaultDate: today.format('YYYY-MM-DD'),
        editable: true,
        locale: 'ko',
        eventLimit: true, // allow "more" link when too many events
        eventSources: [{
            events: function(start, callback){
                var obj = new Object;
                var str_year = start.start.getFullYear();
                var str_month = start.start.getMonth()+1;
                var end_year = start.end.getFullYear();
                var end_month = start.end.getMonth()+1;
                obj.str_year = str_year;
                obj.str_month = str_month;
                obj.end_year = end_year;
                obj.end_month = end_month;
                $.ajax({
                    url: "{% url 'schedule:schedule.monthly_confirmed_order' %}",
                    method:'GET',
                    dataType: 'json',
                    contentType: 'application/json',
                    data : JSON.stringify(obj),
                    processData: false,
                    success: function(result){
                        console.log(result);
                        var events = [];
                        for(var i=0; i<result.length; i++){
                            events.push({
                                id: result[i].sch_id,
                                title: result[i].order_id,
                                start: dateformat(result[i].work_str_date),
                                end: dateformat(result[i].work_end_date),
                            })
                        }
                        return callback(events);
                    }
                });
            }
        }],
      eventClick: function(info) {
        var data = info.event.title
        $.ajax({
            url:'',
            method:'GET',
            success: function(result){
                $('#activationSettingModal').modal('show');
                $('.modal-title').text(info.event.title);
            },
        });
      }
    });
    calendar.render();


});

</script>



{% endblock %}

jobshop/frontend/templates/schedule/sch_history.html
{% extends "common/header.html" %}
{% block content %}

<!-- DataTales Example -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <form method="get" action="{% url 'schedule:schedule.history' %}">
                    <div class="pknu-table-responsive">
                        <div class="col-lg-12 col-md-4 pknu-searchDate-card">
                            <div class="col-lg-1 col-md-3 pknu-searchDate-dd">
                                <label>스케쥴 일자</label>
                            </div>
                            <div class="col-lg-2 col-md-4 pknu-searchDate-dd" >
                                 <input class="form-control text-center" type="text" name="dateFrom" id="dateFrom" value="{{ dateFrom }}"/>
                            </div>
                            <div class="col-lg-1 col-md-1 pknu-searchDate-dd">~</div>
                            <div class="col-lg-2 col-md-4 pknu-searchDate-dd" style="margin-right:0.4rem;">
                                <input class="form-control text-center" type="text" name="dateTo" id="dateTo" value="{{ dateTo }}"/>
                            </div>
                            <div class="col-pos-right">
                                <button id="searchBtn" href="#" class="btn btn-dark w-100"><i class="fas fa-search mr-1"></i>&nbsp; 검색</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">조회</h6>
    </div>
    <div class="card-body">
        <div class="pknu-table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th scope="col">번호</th>
                        <th scope="col">스케쥴링실행일자</th>
                        <th scope="col">오더일자</th>
                        <th scope="col">작업기한</th>
                        <th scope="col">계획 횟수</th>
                        <th scope="col">차트</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sch in sch_list %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{sch.exe_date}}</td>
                        <td>{{sch.sch_date}}</td>
                        <td>{{sch.work_end_date}}</td>
                        <td>{{sch.max_count}}</td>
                        <td width="130">
                            <a id="chartBtn" href="{% url 'schedule:schedule.history_chart' id=sch.orderid schDate=sch.sch_date %}" target="_blank" class="d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-chart-bar mr-1"></i>간트차트</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div id="css-loader" class="loader loader-default"></div>
<script src="/static/js/jquery.treegrid.min.js"></script>
<script>
    function dateformat(value){
        var year = value.substring(0,4);
        var month = value.substring(4,6);
        var day = value.substring(6,8);
        var date = year + '-' + month + '-' + day;
        return date;
    }

    $(function(){
        const today = moment();
        flatpickr("#dateTo", {
               locale: Flatpickr.l10ns.ko,
               enableTime: false,
               dateFormat: "Y-m-d",
               disableMobile: true,
               // defaultDate: $('#dateTo').val()
               defaultDate: [today.format('YYYY-MM-DD')]
        });
        flatpickr("#dateFrom", {
               locale: Flatpickr.l10ns.ko,
               enableTime: false,
               dateFormat: "Y-m-d",
               disableMobile: true,
               defaultDate: $('#dateFrom').val()
        });

        $('#searchBtn').on('click',function(){
            doSearch(
              $('#dateFrom').val().replace(/\-/g,''),
              $('#dateTo').val().replace(/\-/g,'')
            );
        })

        function doSearch(dateFrom, dateTo){
            $.when(
               $.ajax({url: "{% url 'schedule:schedule_history' %}"})
            ).then(function(_data){
                for(var idx in _data){
                    console.log(_data);
                }
                $('#css-loader').removeClass("is-active");
            })
        }
    });

</script>
{% endblock %}