jobshop/board/urls.py
# board/urls.py

from django.urls import path

from .views import ArticleList, ArticleDetail, ArticleDelete, ArticleCreate, ArticleUpdate

urlpatterns = [
    path('', ArticleList.as_view(), name='index'),
    path('create/', ArticleCreate.as_view(), name='create'),
    path('<int:pk>/', ArticleDetail.as_view(), name='detail'),
    path('<int:pk>/update/', ArticleUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', ArticleDelete.as_view(), name='delete'),
]

jobshop/common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='../templates/main/login.html'), name='login'),
]

jobshop/jobshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from frontend import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('logout/', views.logout, name='logout'),
    path('board/', views.board),
    path('test/', views.test),
    path('nav/', views.nav),
    path('footer/', views.footer),
    path('topbar/', views.topbar),
    path('board/', include('board.urls'), name='board'),
    path('company/', include('company.urls'), name='company'),
    path('schedule/', include('schedule.urls'), name='schedule'),
    path('common/', include('common.urls')),
    path('recommend/', include('recommend.urls')),
    path('order/', include('order.urls'), name='order'),
]
# 파일 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

jobshop/board/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=120, null=False)
    author = models.CharField(max_length=20, null=False)
    content = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name_plural = '게시판' 

    def __str__(self):
        return f'{self.id} / {self.title} / {self.author}'

jobshop/board/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Article

class ArticleList(ListView):
    model = Article
    paginate_by = 5
    ordering = ['id']

class ArticleCreate(CreateView):
    model = Article
    fields = ['title', 'author', 'content']
    success_url = reverse_lazy('index')


class ArticleDetail(DetailView):
    model = Article
    # context_object_name = 'article'


class ArticleUpdate(UpdateView):
    model = Article
    fields = ['title', 'author', 'content']
    success_url = reverse_lazy('index')


class ArticleDelete(DeleteView):
    model = Article
    success_url = reverse_lazy('index')

jobshop/frontend/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
import datetime, json
from datetime import timedelta

# Create your views here.
def index(request):
    template_name = 'main/index.html'

    dateFrom, dateTo = get_dates(request)

    context = {
        'dateFrom': dateFrom,
        'dateTo': dateTo,
        'path': '대시보드',
        'selected': 'ordermanagement'
    }
    return render(request, template_name, context)

def get_dates(request):
    date = datetime.datetime.today() - timedelta(days=3)

    if 'dateFrom' in request.GET:
        date_from = datetime.datetime.strptime(request.GET['dateFrom'], "%Y-%m-%d")
        date_to = datetime.datetime.strptime(request.GET['dateTo'], "%Y-%m-%d")
    else:
        date_from = date
        date_to = datetime.datetime.today()

    return date_from.strftime("%Y-%m-%d"), date_to.strftime("%Y-%m-%d")
# board
def board(request):
    return render(request, 'main/board.html')

# login
# def login(request):
#     return render(request, 'main/login.html')

# logout
def logout(request):
    return render(request, 'common/logout.html')

# nav 메뉴
def nav(request):
    return render(request, 'common/nav.html')

# topbar - 검색 바
def topbar(request):
    return render(request, 'common/topbar.html')

# footer
def footer(request):
    return render(request, 'common/footer.html')

# compregist
def company(request):
    return render(request, 'company/comp_regist.html')

# compregist
def test(request):
    return render(request, 'test.html')

jobshop/frontend/templates/main/board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, -scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Blank</title>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <!-- Custom fonts for this template-->
    <link href="../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="../static/css/sb-admin-2.min.css" rel="stylesheet">
    <script>
        $(document).ready(function() {
            $("#headers").load("/nav");  // 원하는 파일 경로를 삽입하면 된다
            $("#topbar").load("/topbar");  // 원하는 파일 경로를 삽입하면 된다
            $("#footer").load("/footer");  // 원하는 파일 경로를 삽입하면 된다
        });
    </script>
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <ul id="headers" class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"></ul>
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav id="topbar"></nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer id="footer" class="sticky-footer bg-white"></footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="../static/vendor/jquery/jquery.min.js"></script>
    <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="../static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="../static/js/sb-admin-2.min.js"></script>


</body>

</html>

jobshop/frontend/templates/main/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Manufacturing Scheduler</title>
    <!-- CSS files -->
    <link href="/static/css/tabler.min.css" rel="stylesheet"/>
    <link href="/static/css/tabler-flags.min.css" rel="stylesheet"/>
    <link href="/static/css/tabler-payments.min.css" rel="stylesheet"/>
    <link href="/static/css/tabler-vendors.min.css" rel="stylesheet"/>
    <link href="/static/css/demo.min.css" rel="stylesheet"/>
  </head>
  <body  class=" border-top-wide border-primary d-flex flex-column">
    <div class="page page-center">
      <div class="container-tight py-4">
        <div class="text-center mb-4">
            <a href="." class="navbar-brand navbar-brand-autodark"><img src="/static/logo.png" height="36" alt=""></a>
            <h2 class="card-title text-center mb-4">부경대학교 공정 스케줄러 로그인</h2>
        </div>
          <form class="card card-md user" action="{% url 'common:login' %}" method="post" autocomplete="off">
            {% csrf_token %}
            {% include "form_errors.html" %}
          <div class="card-body">
            <div class="mb-3">
                <label class="form-label"><strong>아이디</strong></label>
                <input type="text" name="username" id="username" placeholder="로그인 아이디를 입력하세요." class="form-control" value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label class="form-label"><strong>비밀번호</strong></label>
                <input type="password" class="form-control" name="password" placeholder="비밀번호를 입력하세요." id="password" value="{{ form.password.value|default_if_none:'' }}">
              </div>
            <div class="row d-flex justify-content-between mt-4 mb-2">
                <div class="mb-3">
                   <div class="form-check custom-checkbox ms-1">
                        <input type="checkbox" class="form-check-input" id="basic_checkbox_1">
                        <label class="form-check-label" for="basic_checkbox_1">아이디 기억</label>
                    </div>
                </div>
            </div>
            <div class="form-footer">
              <button type="submit" class="btn btn-dark w-100">로그인</button>
            </div>
          </div>
        </form>

                </div>
            </div>
          </div>
        </div>
    </div>


    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
<!--    <script src="/static/vendor/global/global.min.js"></script>-->
<!--    <script src="/static/js/custom.min.js"></script>-->
<!--    <script src="/static/js/dlabnav-init.js"></script>-->

</body>
</html>